### ISSUE TITLE
Exposed API KEY

### ISSUE THREAD

**Issue by Pupix** [Derpthemeus/ChampionMasteryLookup#1]
You should probably remove your API key from [here](https://github.com/Derpthemeus/ChampionMasteryLookup/blob/master/public/riot.txt) and purge the previous commits so the key doesn't show in the project history. More info [here](https://help.github.com/articles/remove-sensitive-data/)

Cheers,
Pupix.

**Comment by Derpthemeus** [comment]
That's a unique token used to verify the website ownership during the application process for an API key, but is not actually an API key or anything sensitive. Thanks for the concern
