### ISSUE TITLE
Sort by required points to level up

### ISSUE THREAD

**Issue by CodeNGame** [Derpthemeus/ChampionMasteryLookup#13]
Can we add a column to the summoner page to show the required points to level up?
I wrote a script for my use, but i think it would be helpful for others if they are also interested in max leveling all champs.
Script: https://pastebin.com/uxY72LxF

**Comment by Derpthemeus** [comment]
Right now sorting by progress is a bit messed up. It currently sorts champions that are level 1-4 by progress to the next level (as a percentage), but sorts champions that are level 5-6 by progress to the max level. In the upcoming days, I'll try to get some feedback from users about their opinions on sorting by progress (including their opinions on if they want to be able to sort progress by the percentage to next level, the points to the next level, or both), and update the site based on that.

Once I gather some feedback on the issue, are you interested in creating a pull request to add the feature, or are you just suggesting that I add the feature?

**Comment by CodeNGame** [comment]
If you are inclined to add, I can take care of the changes for the feature.

**Comment by Derpthemeus** [comment]
I gathered some feedback, and quite a few people are interested in having a 2nd progress columns. 1 column will be the progress towards the max level, and the other column will be progress towards the next level (by points required to level up).

Are you still interested in adding this feature yourself?

**Comment by CodeNGame** [comment]
Cool. Yep, I ll add the feature sometime next week and follow up here.

**Comment by CodeNGame** [comment]
I have the (tested) changes on my local. What is the next step here? 

PS: I am new to GitHub, I couldn't push to a new remote branch. Without that, I don't see any options to make a PR. Is forking the only way?

**Comment by Derpthemeus** [comment]
You'll need to fork the repository to create a PR. The basic steps are:
1. Fork the repo
2. Push your changes to the forked repo
3. Make a pull request from the forked repo to the original repo

[You can find more detailed instructions here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by CodeNGame** [comment]
Thanks. Created the PR.

**Comment by Derpthemeus** [comment]
Thanks for your contribution!
