### ISSUE TITLE
Unable to run the server locally

### ISSUE THREAD

**Issue by CodeNGame** [Derpthemeus/ChampionMasteryLookup#14]
I am trying make changes for the other feature request I created. When I compile and run "npm start", I get an error "VError: CRITICAL ERROR UPDATING STATIC DATA: Error updating static data: Received 403 code for https://ddragon.leagueoflegends.com/cdn/dragontail-7.20.3.tgz".

Hitting the url directly is throwing a 403 as well. Am I missing something here?

On a side note: I have added my RIOT API key to the config, but I dont think it is even needed for the above cdn request.

**Comment by Derpthemeus** [comment]
You're not missing anything; static data (the source for champion icons and profile icons) is currently down. try again later and see if it works.

Also, I'd suggest holding off on making changes. I want to gather some feedback on the issue from more users to determine exactly how the feature should be setup.

**Comment by CodeNGame** [comment]
Is there anyway to check the API status? I am not able to find this url in Riot developer portal as well.

On the latter, I ll wait for your comments on the feature. I am just playing with the setup and the code.

**Comment by Derpthemeus** [comment]
There isn't a status tracker for DDragon because it isn't part of the API. It's available for developers to use, but it isn't maintained by the API team at Riot.

If you're interested, there's more info about DDragon here: https://developer.riotgames.com/static-data.html

**Comment by CodeNGame** [comment]
ddragon is back up.
