### ISSUE TITLE
cant access api anymore?

### ISSUE THREAD

**Issue by borgified** [Derpthemeus/ChampionMasteryLookup#16]
curl "http://championmasterylookup.derpthemeus.com/summoner/?summoner=thradash&region=NA"

results in:

An error has occurred
API error (400)
Try refreshing the page. If the problem persists, let me know (contact info in site footer).

**Comment by Derpthemeus** [comment]
This is caused by an issue with Riot's API. They are aware of the issue, and it will likely be resolved soon.
