### ISSUE TITLE
CSS issue.

### ISSUE THREAD

**Issue by achpile** [Derpthemeus/ChampionMasteryLookup#17]
Hi. Recently I updated my firefox and not earned stuff looks like a black square now.

`.notEarned {
	filter: brightness(0%) opacity(15%);
	-webkit-filter: brightness(0%) opacity(15%);
}`

If I set brightness to 100% - it looks normal (like it should be). Tested on older version of Firefox, but not sure about other browsers.

**Comment by achpile** [comment]
![_2018-11-14_11-57-50](https://user-images.githubusercontent.com/6649598/48471248-86919080-e804-11e8-8380-1f73db936a15.png)

**Comment by Derpthemeus** [comment]
Thanks for the report! The fix should be deployed later today or tomorrow
