### ISSUE TITLE
Highscores Specific Champion list

### ISSUE THREAD

**Issue by NormanDubert** [Derpthemeus/ChampionMasteryLookup#2]
when searching people, it should move someone down a spot on the high score list, instead it just overwrites the previous person that was at that spot.

**Comment by Derpthemeus** [comment]
It should do this but I have gotten numerous reports that it doesn't. I can't seem to figure out the problem, but I'm guessing it has something to do with concurrency (which I don't know too much about). The offending code is most likely [this](https://github.com/Derpthemeus/ChampionMasteryLookup/blob/master/server.js#L310) if anyone is interested

**Comment by NormanDubert** [comment]
nah, it's not concurrency. are you using the splice method correctly? I don't know javascript but the two i looked up said it was splice(index, how many to be removed, elements). so instead of doing "highscores[championId].length - HSCOUNT.track + 1", just use 0 and then remove the element at the end of the array on another line.

**Comment by Derpthemeus** [comment]
It would appear that I screwed it up at some point (I swear there was a point it was working). Thanks a bunch, this should be resolved shortly
