### ISSUE TITLE
Wrong Data

### ISSUE THREAD

**Issue by dmeskill** [Derpthemeus/ChampionMasteryLookup#6]
I use your website all the time to compare my score to the top 20 world Orianna players. But I noticed one player "Back To Paradise (NA)" on the top 20 list has a mastery of 405,762 when in reality on his profile (I also checked him through league client) he only has a mastery of 210,355. He does not deserve to be on the top 20 list and not sure why the data on the high-score 20 is wrong

**Comment by Derpthemeus** [comment]
It looks like that player changed their name and somebody else took their old name. I've fixed this occurrence of the problem and will look into automating the fix. Thanks for the report!

**Comment by dmeskill** [comment]
Thanks for being on top of everything and taking care of all of these so quickly. I like the new layout and new features also! Keep up the good work!
